# NumPy

NumPy is a Linear Algebra Library for Python. NumPy arrays can represent vectors (1-d) or matrixes (2-d).

## List of NumPy functions:
* np.array: converts Python lists into NumPy arrays.
* np.arange: creates a NymPy array with number within the range.
* np.zeros: creates a NymPy filled with zeros.
* np.ones: creates a NymPy filled with ones.
* np.linspace: creates a NymPy filled with evenly spaced numbers.
* np.eye: creates identity matrix.
* np.random: contains useful random functions.

## List of NumPy array functions:
* arr.reshape: changes the dimensions of the array.
* arr.max: returns the max value of the array.
* arr.min: returns the min value of the array.
* arr.argmax: returns the index value (location) of the max value of the array.
* arr.argmin: returns the index value (location) of the min value of the array.
* arr.sum: returns a sum of all elements, row totals (axis=1) or column totals (axis=0).
* arr.copy: creates a copy of the array or array slice. By default, NumPy assign arrays/slices to new variables by reference.

## List of NumPy array attributes:
* arr.shape: shape of the array.
* arr.dtype: data type in the array.

## NumPy operations
* Array with Array: element by element basis.
* Array with Scalars: broadcasts to all array elements.
* Universal Array Functions: [list of universal funcitons](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs).


## Usage examples

In [1]:
# Using NumPy
import numpy as np

### Creating NumPy arrays from Python list

In [2]:
# Vector from Python list

my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
# Matrix from Python list
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Creating NumPy arrays using built-in functions

In [4]:
# np.arange
np.arange(0, 10) # start, stop, step

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# np.arange
np.arange(0, 11, 2) # start, stop, step

array([ 0,  2,  4,  6,  8, 10])

In [6]:
# np.zeros
np.zeros(5) # Integer for 1-d dimension

array([0., 0., 0., 0., 0.])

In [7]:
# np.zeros
np.zeros((2,3)) # Tuple for 2-d dimension: rows, columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# np.ones
np.ones(5) # Integer for 1-d dimension

array([1., 1., 1., 1., 1.])

In [9]:
# np.ones
np.ones((2,3)) # Tuple for 2-d dimension: rows, columns

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# np.linspace
np.linspace(0, 5, 10) # start, stop, num of desired points

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
# np.eye
np.eye(4) # Dimension

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Generating random matrixes
#### Uniform distribution

In [12]:
np.random.rand(5) # 1-d

array([0.14080838, 0.22593244, 0.70097606, 0.53734361, 0.0940652 ])

In [13]:
np.random.rand(5,4) # 2-d

array([[0.8702404 , 0.44639664, 0.77162139, 0.86799737],
       [0.52279097, 0.04263836, 0.1266194 , 0.85765569],
       [0.55474923, 0.62068386, 0.99820415, 0.3120384 ],
       [0.85459087, 0.58586269, 0.54901023, 0.94422966],
       [0.90429628, 0.79421699, 0.65611074, 0.37278333]])

#### Normal distribution

In [14]:
np.random.randn(5) # 1-d

array([-1.18464161,  0.33564668, -0.46583353,  0.02271284,  0.86693858])

In [15]:
np.random.randn(4,3) # 2-d

array([[ 1.01645196,  1.25073671, -1.20337318],
       [ 1.53629437, -0.95726863, -1.08621743],
       [ 2.52183165, -2.18553193, -0.39234169],
       [-1.88772162,  0.2038858 , -0.92607406]])

#### Random integers within an interval

In [16]:
np.random.randint(1,100, 4) # low, high, num of desired points

array([73, 34, 40,  6])

### NumPy functions

In [17]:
# reshape
arr = np.arange(25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
# max
arr.max()

24

In [19]:
# min
arr.min()

0

In [20]:
# argmax
arr.argmax()

24

In [21]:
# argmin
arr.argmin()

0

In [22]:
# sum
arr.reshape(5,5).sum()

300

In [23]:
# sum row (row totals)
arr.reshape(5,5).sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [24]:
# sum col (column totals)
arr.reshape(5,5).sum(axis=0)

array([50, 55, 60, 65, 70])

In [25]:
# Copy
original = np.arange(0,11)           # [0,1,2,3,4,5,6,7,8,9,10]
ref_of_array = original[:5]          # [0,1,2,3,4]
copy_of_array = original[5:].copy()  # [5,6,7,8,9,10]
ref_of_array[:] = 99                 # [99,99,99,99]
copy_of_array[:] = 100               # [100,100,100,100,100]
print("Reference array: {}".format(ref_of_array))
print("Copy array: {}".format(copy_of_array))
print("Original array affected by changes made in reference array: {}".format(original))

Reference array: [99 99 99 99 99]
Copy array: [100 100 100 100 100 100]
Original array affected by changes made in reference array: [99 99 99 99 99  5  6  7  8  9 10]


### NumPy attributes
(Note: attributes do not use parenthesis)

In [26]:
# shape
arr.shape

(25,)

In [27]:
# dtype
arr.dtype

dtype('int32')

### Selecting from NumPy arrays
#### Using slice notation

In [28]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
# Select top right corner
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [30]:
# Select right column
arr_2d[:,2]

array([15, 30, 45])

In [31]:
# Select middle row
arr_2d[1,:]

array([20, 25, 30])

In [32]:
# Select middle & bottom from middle column
arr_2d[1:,1]

array([25, 40])

#### Conditional selection

In [33]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
# Using comparison operators will create a new boolean array
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [35]:
# The above boolean array can be used to select array elements
arr[arr > 5] # Selects only when comparison returns True

array([ 6,  7,  8,  9, 10])

### NumPy Operations

In [36]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
# Array with Array
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [40]:
arr_2d = arr.reshape(2,5).copy()
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
arr_2d + arr_2d

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [42]:
arr_2d - arr.reshape(2,5)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [43]:
# Array with Scalars
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [44]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)